DELETE FROM [User]
DBCC CHECKIDENT('User', RESEED, 0);

DELETE FROM [Friend]
DBCC CHECKIDENT('Friend]', RESEED, 0);

DELETE FROM [Stick]
DBCC CHECKIDENT('Stick', RESEED, 0);

DELETE FROM [Tags]
DBCC CHECKIDENT('Tags', RESEED, 0);

DELETE FROM [TextCheck]
DBCC CHECKIDENT('TextCheck', RESEED, 0);